Loadouts-Nato Desert
Synixe/Synixe pull request #2
Opened 2019-09-18 05:52 UTC by SynixePac

2019-09-18 05:53 UTC, BrettMayson requested changes

2019-09-18 05:53 UTC, synixebrett commented on addons/loadouts/loadouts/NATO.hpp
> +         AutoRifleman = QUOTE([["CUP_lmg_m249_pip1","muzzle_snds_m_snd_F","","CUP_optic_ElcanM145",["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",200],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight
```suggestion
        AutoRifleman = QUOTE([["CUP_lmg_m249_pip1","muzzle_snds_m_snd_F","","CUP_optic_ElcanM145",["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",200],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pistol","",["CUP_17Rnd_9x19_glock17",17],[],""],["CFP_U_FieldUniform_marpat_d",[["ACRE_PRC343",1],["ACE_elasticBandage",3],["ACE_EarPlugs",1],["ACE_morphine",3],["ACE_packingBandage",3],["SmokeShell",1,1],["CUP_HandGrenade_M67",1,1]]],["SP_PlateCarrier1_Tan",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",1,200],["MiniGrenade",1,1]]],["CFP_AssaultPack_MarpatDesert",[["CUP_200Rnd_TE4_Green_Tracer_556x45_M249",2,200]]],"CUP_H_USMC_MICH2000_DEF_ESS_DES","CUP_PMC_Facewrap_Tan",[],["ItemMap","","","ItemCompass","ItemWatch","CUP_NVG_PVS14"]])
```

2019-09-18 06:18 UTC, synixebrett commented
This should probably be named MARPAT Desert instead of just Desert

2019-09-18 06:21 UTC, BrettMayson requested changes

2019-09-18 06:21 UTC, synixebrett commented on addons/loadouts/loadouts/NATO.hpp
> +        Squad_Leader = QUOTE([["CUP_arifle_M4A1_BUIS_desert_GL","CUP_muzzle_snds_M16","","CUP_optic_ACOG",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pist
- No vanilla mine detector
- No Packing Bandages
- No morphine
- Needs tourniquet

2019-10-05 21:44 UTC, SynixePac commented on addons/loadouts/loadouts/NATO.hpp
> +        Squad_Leader = QUOTE([["CUP_arifle_M4A1_BUIS_desert_GL","CUP_muzzle_snds_M16","","CUP_optic_ACOG",["CUP_30Rnd_556x45_PMAG_QP_Tan",30],[],""],[],["CUP_hgun_Glock17_tan","","acc_flashlight_pist
-Removed Morphine from everyone Except Medic
-Gave out Tourniquets
-Replaced Vanilla Mine Detector with ACE
-Replaced Packing Bandages with Elastic

2019-10-07 02:15 UTC, synixebrett commented
Looks fine, I'll need to fix the ID'd radios before merge

2019-10-31 04:10 UTC, BrettMayson approved these changes

2019-10-31 04:15 UTC, merged