Added Police Loadouts
Synixe/Synixe pull request #3
Opened 2019-10-31 05:11 UTC by SynixePac

2019-10-31 05:19 UTC, BrettMayson requested changes

2019-10-31 05:19 UTC, synixebrett commented on addons/loadouts/loadouts/police.hpp
> +		Walther P99 = [[],[],["tacs_Walther_P99","","","",["16Rnd_9x21_Mag",17],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACR
Needs to be `Walther_P99`

2019-10-31 05:22 UTC, SynixePac commented on addons/loadouts/loadouts/police.hpp
> +		Walther P99 = [[],[],["tacs_Walther_P99","","","",["16Rnd_9x21_Mag",17],[],""],["U_I_P_PoliceUniform_01_F",[["ACE_elasticBandage",5],["ACE_CableTie",3],["ACE_EarPlugs",1],["ACE_tourniquet",2],["ACR
resolved

2019-11-06 01:46 UTC, BrettMayson approved these changes

2019-11-06 01:46 UTC, merged